package com.example.demo.enums;

public enum ErrorCodeEnum {
	USER_NOT_FOUND, INVALID_CREDENTIALS, ROLE_NOT_FOUND, PERMISSION_NOT_FOUND, TOKEN_INVALID, TOKEN_EXPIRED,
	VALIDATION_FAILED, PASSWORD_MISMATCH, BAD_REQUEST, INTERNAL_ERROR
}
