package com.example.demo.enums;

public enum PermissionEnum {

	EMPLOYEE_READ, EMPLOYEE_WRITE, EMPLOYEE_DELETE, EMPLOYEE_LIST,

	ATTENDANCE_MARK, ATTENDANCE_VIEW,

	LEAVE_APPLY, LEAVE_APPROVE,

	PAYROLL_VIEW, PAYROLL_RUN;

}
